apiVersion: v1
kind: Pod
metadata:
  name: cowrie
  labels:
    app.kubernetes.io/name: cowrie
    app.kubernetes.io/instance: cowrie-abcxzy
    app.kubernetes.io/component: honeypot
    app.kubernetes.io/part-of: cowrie
spec:
  volumes:
    - name: cowrie-var
      emptyDir: {}
    - name: cowrie-etc
      emptyDir: {}
    - name: cowrie-logs
      hostPath:
        path: /data/cowrie-log/  # Change this to your desired local directory
        type: DirectoryOrCreate  # This will create the directory if it doesn't exist
  containers:
    - name: cowrie
      image: cowrie/cowrie:latest
      imagePullPolicy: Always
      securityContext:
        runAsUser: 999
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - all
      ports:
        - name: ssh-port
          containerPort: 2222
        - name: telnet-port
          containerPort: 2223
      readinessProbe:
        tcpSocket:
          port: ssh-port
        initialDelaySeconds: 5
        periodSeconds: 60
      livenessProbe:
        tcpSocket:
          port: ssh-port
        initialDelaySeconds: 15
        periodSeconds: 60
      #volumeMounts:
       # - name: cowrie-logs
         # mountPath: /cowrie/cowrie-git/var  # This is the log path inside the container
          