apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk-stack
data:
  # configuration for logstash pipeline
  logstash.conf: |
    input {
      filestream {
      port => 5000
      }
    }


    filter {
        if [type] == "cowrie" {
      #       json {
      #     source => message
      #           target => honeypot
      # }

            date {
                match => [ "timestamp", "ISO8601" ]
            }

            if [honeypot][src_ip]  {

                mutate {
                   # add_field => { "src_host" => "%{[honeypot][src_ip]}" }
                }

                dns {
                    reverse => [ "src_host" ]
                    nameserver => [ "8.8.8.8", "8.8.4.4" ]
                    action => "replace"
                    hit_cache_size => 4096
                    hit_cache_ttl => 900
                    failed_cache_size => 512
                    failed_cache_ttl => 900
                }


                geoip {
                    source => "[honeypot][src_ip]"
                    target => "geoip"
                  # database => "/opt/logstash/vendor/geoip/GeoLite2-City.mmdb"
                }

            }

            mutate {
          # cut out useless tags/fields
                remove_tag => [ "beats_input_codec_plain_applied"]
          remove_field => [ "[log][file][path]", "[log][offset]" ]
            }
        }
    }
        output {
      if [type] == "cowrie" {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]  # Use Kubernetes service name
          user => "elastic"
          index => "cowrie-logs-%{+YYYY.MM.dd}"
          # password => "K+=-*vyESYjWEYG6l9D8"
          # ssl => true
          # cacert => "/etc/logstash/certs/http_ca.crt"
          ilm_enabled => auto
          ilm_rollover_alias => "cowrie-logstash"
        }

        stdout {
          codec => rubydebug
        }
      }
    }

  
  # logstash configuration
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline